### ISSUE TITLE
feat: support dark theme

### ISSUE THREAD

**Issue by iget-master** [expressots/expresso-site-doc#11]
I was reading the docs on mobile, and noticed that the documentation is in a blinding white theme.

I think that's not a hard thing to do, but very useful for our tired eyes.

**Comment by ArielBetti** [comment]
The documentation is currently made with Docssauros, there is a whole documentation on how to change the theme and make a custom.
I'll leave it here for anyone who wants to contribute to this task.

Docssauros documentation
https://docusaurus.io/docs/api/themes/configuration

Figma ExpressoTS Style Guide:
https://www.figma.com/file/zR5GtrUTtJmPpO3XVuK9Vc/%5BExpressoTS%5D-Brand-Design?type=design&node-id=126-256&mode=design&t=juTPWUBtBUlTLZG5-0

Implementation example with css:
https://github.com/expressots/expressots-site/blob/main/src/globals.css

**Comment by rsaz** [comment]
Item completed in PR #14.
Closing the issue as the feature is already available.
