### ISSUE TITLE
Translate the doc to Spanish

### ISSUE THREAD

**Issue by rsaz** [expressots/expresso-site-doc#29]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is no documentation translated to Spanish

### Steps to reproduce

N/A

### Expected behavior

New doc version in Spanish

### Package version

N/A

### Node.js version

N/A

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by cristopherpds** [comment]
Esta es mi oportunidad... 🚀

**Comment by rsaz** [comment]
> Esta es mi oportunidad... 🚀

Let me know if you're going to work on this task so that I can assign the ticket to you

**Comment by cristopherpds** [comment]
Of course, start working on it

**Comment by IrkenStudio** [comment]
I noticed that this translation wasn't worked on for a month. I would like to work on the translation.
