### ISSUE TITLE
Adjust the methods name on Controller section

### ISSUE THREAD

**Issue by rsaz** [expressots/expresso-site-doc#32]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Existing Issues

N/A

### Current behavior

Controller and parameter decorators are not correct. They are shown the previous version of ExpressoTS
[Here is incorrect page](https://doc.expresso-ts.com/docs/overview/controller#controller-decorators)

INCORRECT
![image](https://github.com/expressots/expresso-site-doc/assets/4088378/b8a10f44-a0a1-4e5b-8526-2fe5dcc8c727)

[In this page](https://doc.expresso-ts.com/docs/overview/decorators) decorators page, contain all the controller and parameters decorators that are correct and should be used in the above page.

CORRECT
![image](https://github.com/expressots/expresso-site-doc/assets/4088378/c11d3c8d-20f4-456e-a666-102185d4132f)

### Steps to reproduce

N?A

### Expected behavior

Replace the decorators in the Controller section by the ones in the Decorators section

### Package version

N/A

### Node.js version

N/A

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by dotarjun** [comment]
I'd like to work on this

**Comment by rsaz** [comment]
> I'd like to work on this

Ticket assigned to you. Looking forward to receive your submission

**Comment by rsaz** [comment]
Good job!
